server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  application:
    name: uavs
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:uavs}
    username: ${DB_USERNAME:uavs_user}
    password: ${DB_PASSWORD:uavs_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI:http://localhost:9000}
          jwk-set-uri: ${OAUTH_JWK_SET_URI:http://localhost:9000/.well-known/jwks.json}

  vault:
    host: ${VAULT_HOST:localhost}
    port: ${VAULT_PORT:8200}
    scheme: ${VAULT_SCHEME:http}
    authentication: token
    token: ${VAULT_TOKEN:dev-token}
    kv:
      enabled: true
      backend: secret
      application-name: uavs

logging:
  level:
    com.company.uavs: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

uavs:
  vendor:
    timeouts:
      connection: 3000
      read: 3000
      total: 10000
    retry:
      max-attempts: 3
      backoff-multiplier: 2
      initial-interval: 1000
    
  stellr:
    base-url: ${STELLR_BASE_URL:https://api.stellr.com}
    timeout: 3000
    
  mcafee:
    base-url: ${MCAFEE_BASE_URL:https://api.mcafee.com}
    timeout: 3000
    
  safehouse:
    base-url: ${SAFEHOUSE_BASE_URL:https://api.safehouse.com}
    timeout: 3000
    
  qwiksilver:
    base-url: ${QWIKSILVER_BASE_URL:https://api.qwiksilver.com}
    timeout: 3000

  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,OPTIONS
      allowed-headers: "*"
      max-age: 3600

  monitoring:
    synthetic-tests:
      enabled: ${SYNTHETIC_TESTS_ENABLED:true}
      interval: 3600000 # 1 hour
    
  compliance:
    data-retention:
      card-number-days: 30
      audit-log-years: 7