server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  datasource:
    url: jdbc:h2:mem:uavs;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev-h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    defer-datasource-initialization: true
  liquibase:
    enabled: false

logging:
  level:
    com.company.uavs: INFO
    org.springframework.security: WARN
