global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "uavs_rules.yml"

scrape_configs:
  - job_name: 'uavs'
    static_configs:
      - targets: ['uavs:8080']
    metrics_path: '/v1/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093